[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/graph-gophers/graphql-go"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.1"
